# Base configs
baseurl: "/profileflat/"

# UI configs
title: "Vatsal Mistry"
author: "Vatsal Mistry"
about: "A Pythonista"
social_urls:
  facebook: "https://www.facebook.com/mistryvatsal"
  twitter: "https://www.twitter.com/mistryvatsal11"
  instagram: "https://www.instagram.com/mistryvatsal42"
